input_channels: 1
conv_channels: [32, 64, 128, 256]
kernel_size: 7
pool_size: 2
dropout_cnn: 0.3
lstm_hidden_size: 512
lstm_layers: 2
dropout_lstm: 0.3
seq_len: 1000

batch_size: 128
val_split: 0.9
num_epochs: 50
learning_rate: 0.0001

seed: 1000